spring:
  cloud:
    bus:
      ack:
        destination-service: ${spring.application.name}
        
# 单机模式配置
---
spring:
  profiles: develop
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
# 使用feign+hystrix断路时必须增加以下配置，否则不会生效
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.web: INFO

# 集群模式配置
---
spring:
  profiles: production
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@yiran-base-eureka-s1.base.svc.cluster.local:8761/eureka/, http://admin:admin@yiran-base-eureka-s2.base.svc.cluster.local:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true 
# 使用feign+hystrix断路时必须增加以下配置，否则不会生效
feign:
  hystrix:
    enabled: true  
logging:
  level:
    org.springframework.web: INFO    