spring:
  cloud:
    bus:
      ack:
        destination-service: ${spring.application.name}
eureka:
  server:
    enable-self-preservation: false
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
logging:
  level:
    org.springframework.web: INFO