spring:
  cloud:
    bus:
      ack:
        destination-service: ${spring.application.name}

# 单机模式配置
---
spring:
  profiles: develop

  redis:
    redisson: false
#    host: 114.67.224.99
#    port: 6379
    host: 127.0.0.1
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.79.188.227:3306/microservice?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: db_sc
    password: bitlife_db_sc_888T3!
    druid:
      stat-view-servlet:
        enabled: true
        #通过子网掩码设置IP段
        allow: 127.0.0.1,192.168.40.0/24
        deny: 192.168.40.20/32
        login-username: druid
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true  
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
   
security:
  oauth2:
    authorization:
      matchers: /load/**, /swagger-ui.html, /webjars/**, /swagger-resources/**, /v2/api-docs, /static/**
    client:
      scope: webclient
      clientId: eagleeye
      clientSecret: thisissecret
      accessTokenUri: http://127.0.0.1:8887/oauth/token
      userAuthorizationUri: http://127.0.0.1:8887/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8887/oauth/token_key 

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: hystrix.stream, health, info
                
logging:
  level:
    org.springframework.web: INFO
    root: INFO
    org.hibernate: INFO

# 集群模式配置
---
spring:
  profiles: production

  redis:
    redisson: false
    host: redis-standalone.base.svc.cluster.local
    port: 6379
    
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mysql-standalone.base.svc.cluster.local:3306/microservice?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: microservice
    password: bitlife_microservice_888T3!
    druid:
      stat-view-servlet:
        enabled: true
        #通过子网掩码设置IP段
        allow: 127.0.0.1,192.168.40.0/24
        deny: 192.168.40.20/32
        login-username: druid
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true  
  client:
    service-url:
      defaultZone: http://admin:admin@yiran-base-eureka-s1.base.svc.cluster.local:8761/eureka/, http://admin:admin@yiran-base-eureka-s2.base.svc.cluster.local:8761/eureka/

security:
  oauth2:
    authorization:
      matchers: /load/**, /swagger-ui.html, /webjars/**, /swagger-resources/**, /v2/api-docs, /static/**
    client:
      scope: webclient
      clientId: eagleeye
      clientSecret: thisissecret
      accessTokenUri: http://yiran-base-authorization.base.svc.cluster.local:8887/oauth/token
      userAuthorizationUri: http://yiran-base-authorization.base.svc.cluster.local:8887/oauth/authorize
    resource:
      jwt:
        key-uri: http://yiran-base-authorization.base.svc.cluster.local:8887/oauth/token_key 

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: hystrix.stream, health, info
        
logging:
  level:
    org.springframework.web: INFO
    root: INFO
    org.hibernate: INFO